# Generated by Django 5.2.2 on 2025-06-11 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0005_alter_recipeingredient_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.PositiveIntegerField()),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="products.recipe",
                        verbose_name="Passos de Receita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passo de Receita",
                "verbose_name_plural": "Passos de Receita",
                "ordering": ["recipe", "num"],
            },
        ),
    ]
