# Generated by Django 5.2.2 on 2025-06-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufature", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Processamento",
                "verbose_name_plural": "Tipo de Processamento",
                "ordering": ["name"],
            },
        ),
    ]
