# Generated by Django 5.2.2 on 2025-06-11 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufature", "0002_processingtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipestep",
            name="processing_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipes",
                to="manufature.processingtype",
                verbose_name="Tipo de Processamento",
            ),
        ),
    ]
