# Generated by Django 5.2.2 on 2025-06-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufature", "0003_recipestep_processing_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipestep",
            name="description",
            field=models.CharField(blank=True, null=True, verbose_name="Descrição"),
        ),
    ]
