# Generated by Django 5.2.2 on 2025-06-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufature", "0004_alter_recipestep_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingtype",
            name="enable_baking_pan",
            field=models.BooleanField(
                default=False, verbose_name="Requer Forma de Assar"
            ),
        ),
    ]
