# Generated by Django 5.2.2 on 2025-06-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufature", "0005_processingtype_enable_baking_pan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="processingtype",
            old_name="enable_baking_pan",
            new_name="require_baking_pan",
        ),
    ]
