# Generated by Django 5.2.2 on 2025-06-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manufature",
            "0006_rename_enable_baking_pan_processingtype_require_baking_pan",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipestep",
            name="num",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
