# Generated by Django 5.2.2 on 2025-06-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufature", "0007_alter_recipestep_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipestep",
            name="processing_type",
        ),
        migrations.RemoveField(
            model_name="recipestep",
            name="recipe",
        ),
        migrations.DeleteModel(
            name="ProcessingType",
        ),
        migrations.DeleteModel(
            name="RecipeStep",
        ),
    ]
