# Generated by Django 5.2.2 on 2025-06-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderitem_flavor_1_orderitem_flavor_2_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["order", "product"],
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
            },
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity",
        ),
    ]
