# Generated by Django 5.2.2 on 2025-06-10 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_orderitem_options_remove_orderitem_quantity"),
        ("products", "0004_productdatasheet_baking_pan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="flavor_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items_flavor_1",
                to="products.flavor",
                verbose_name="Sabor 1",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="flavor_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items_flavor_2",
                to="products.flavor",
                verbose_name="Sabor 2",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="flavor_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items_flavor_3",
                to="products.flavor",
                verbose_name="Sabor 3",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="flavor_4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items_flavor_4",
                to="products.flavor",
                verbose_name="Sabor 4",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="flavor_5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items_flavor_5",
                to="products.flavor",
                verbose_name="Sabor 5",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="products.product",
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity_1",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Quantidade Sabor 1"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity_2",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Quantidade Sabor 2"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity_3",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Quantidade Sabor 3"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity_4",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Quantidade Sabor 4"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity_5",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Quantidade Sabor 5"
            ),
        ),
    ]
