# Generated by Django 5.2.2 on 2025-06-10 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_orderitem_flavor_1_alter_orderitem_flavor_2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="flavor_1",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="flavor_2",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="flavor_3",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="flavor_4",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="flavor_5",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity_1",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity_2",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity_3",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity_4",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity_5",
        ),
    ]
