# Generated by Django 5.2.2 on 2025-06-10 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_orderitem_flavor_1_remove_orderitem_flavor_2_and_more"),
        ("products", "0005_alter_recipeingredient_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItemFlavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade Sabor"
                    ),
                ),
                (
                    "flavor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_item_flavors",
                        to="products.flavor",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flavors",
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sabor do Item do Pedido",
                "verbose_name_plural": "Sabores do Item do Pedido",
                "ordering": ["order_item", "flavor"],
                "unique_together": {("order_item", "flavor")},
            },
        ),
    ]
