# Generated by Django 5.2.2 on 2025-06-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_orderitemflavor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(verbose_name="Data Agndada"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_time",
            field=models.CharField(
                default="00:00-00:30", verbose_name="Horário agendado"
            ),
        ),
    ]
