# Generated by Django 5.2.2 on 2025-06-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_order_delivery_date_alter_order_delivery_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_time",
            field=models.CharField(verbose_name="Horário agendado"),
        ),
    ]
