# Generated by Django 5.2.2 on 2025-06-15 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_order_delivery_time"),
        ("products", "0009_alter_productdatasheetrecipe_multiple"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ext_product_code",
                    models.CharField(
                        max_length=100, verbose_name="Código do produto externo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation",
                        to="products.product",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tradução de Produto",
                "verbose_name_plural": "Tradução de Produtos",
                "ordering": ["ext_product_code"],
            },
        ),
    ]
