# Generated by Django 5.2.2 on 2025-06-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_externalproduct_delete_producttranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.FloatField(default=1, verbose_name="Quantidade"),
        ),
    ]
