# Generated by Django 5.2.2 on 2025-06-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_orderitem_quantity"),
        ("products", "0009_alter_productdatasheetrecipe_multiple"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalproduct",
            name="flavor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translation",
                to="products.flavor",
                verbose_name="Produto",
            ),
        ),
    ]
