# Generated by Django 5.2.2 on 2025-06-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_externalproduct_flavor"),
        ("products", "0009_alter_productdatasheetrecipe_multiple"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalproduct",
            name="ext_addon_code",
            field=models.CharField(
                default="-", max_length=100, verbose_name="Código do addon"
            ),
        ),
        migrations.AddField(
            model_name="externalproduct",
            name="ext_selection_code",
            field=models.CharField(
                default="-", max_length=100, verbose_name="Código da Seleção"
            ),
        ),
        migrations.AlterField(
            model_name="externalproduct",
            name="flavor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translation",
                to="products.flavor",
                verbose_name="Sabor",
            ),
        ),
    ]
