# Generated by Django 5.2.2 on 2025-06-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_externalproduct_ext_addon_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproduct",
            name="ext_product_code",
            field=models.CharField(
                default="-", max_length=100, verbose_name="Código do produto externo"
            ),
        ),
    ]
