# Generated by Django 5.2.2 on 2025-06-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_alter_externalproduct_ext_product_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproduct",
            name="ext_addon_code",
            field=models.CharField(max_length=100, verbose_name="Código do addon"),
        ),
        migrations.AlterField(
            model_name="externalproduct",
            name="ext_selection_code",
            field=models.CharField(max_length=100, verbose_name="Código da Seleção"),
        ),
    ]
