# Generated by Django 5.2.2 on 2025-06-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_alter_externalproduct_ext_addon_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalproduct",
            name="translate_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flavor", "Sabor"),
                    ("product_flavor", "Sabor e Produto"),
                    ("product", "Produto"),
                    ("ignore", "Ignorar"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="externalproduct",
            name="ext_addon_code",
            field=models.CharField(max_length=255, verbose_name="Código do Adicional"),
        ),
        migrations.AlterField(
            model_name="externalproduct",
            name="ext_product_code",
            field=models.CharField(
                max_length=255, verbose_name="Código do produto externo"
            ),
        ),
        migrations.AlterField(
            model_name="externalproduct",
            name="ext_selection_code",
            field=models.CharField(max_length=255, verbose_name="Código da Seleção"),
        ),
    ]
