# Generated by Django 5.2.2 on 2025-06-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_externalproduct_translate_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalproduct",
            name="translate_type",
        ),
    ]
