# Generated by Django 5.2.2 on 2025-06-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_remove_externalproduct_translate_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalproduct",
            name="validated",
        ),
    ]
