# Generated by Django 5.2.2 on 2025-06-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_remove_externalproduct_validated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="externalproduct",
            options={
                "ordering": [
                    "ext_product_code",
                    "ext_addon_code",
                    "ext_selection_code",
                ],
                "verbose_name": "Tradução de Produto",
                "verbose_name_plural": "Tradução de Produtos",
            },
        ),
    ]
