# Generated by Django 5.2.2 on 2025-06-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_alter_externalproduct_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_num",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número do Pedido"
            ),
        ),
        migrations.AlterField(
            model_name="orderitemflavor",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Quantidade Sabor"
            ),
        ),
    ]
