# Generated by Django 5.2.2 on 2025-06-17 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0025_alter_orderitem_product"),
        ("products", "0012_alter_productdatasheetrecipe_measure_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="products.product",
                verbose_name="Produto",
            ),
        ),
    ]
