# Generated by Django 5.2.2 on 2025-06-17 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_alter_orderitem_product"),
        ("products", "0012_alter_productdatasheetrecipe_measure_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("em_preparacao", "Em Preparação"),
                    ("agendado", "Agendado"),
                    ("cancelado", "Cancelado"),
                    ("concluido", "Concluído"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="externalproduct",
            name="flavor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="products.flavor",
                verbose_name="Sabor",
            ),
        ),
        migrations.AlterField(
            model_name="externalproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="products.product",
                verbose_name="Produto",
            ),
        ),
    ]
