# Generated by Django 5.2.2 on 2025-06-09 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "yield_measure",
                    models.CharField(
                        max_length=100, verbose_name="Medida de Rendimento"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "prd_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Ingrediente"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Ingrediente",
                "verbose_name_plural": "Ingredientes",
                "db_table": "man_ingredient",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MeasureUnit",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Código da Unidade",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nome da Unidade"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Unidade de Medida",
                "verbose_name_plural": "Unidades de Medida",
                "db_table": "gen_measure_unit",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("production_date", models.DateField(verbose_name="Data de Produção")),
            ],
            options={
                "verbose_name": "Lote de Produção",
                "verbose_name_plural": "Lotes de Produção",
                "db_table": "man_production_batch",
                "ordering": ["production_date"],
            },
        ),
        migrations.CreateModel(
            name="RecipeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Categoria de Receita",
                "verbose_name_plural": "Categorias de Receita",
                "db_table": "man_recipe_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Flavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Sabor"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flavors",
                        to="products.category",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sabor",
                "verbose_name_plural": "Sabores",
                "db_table": "prd_flavor",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "yield_quantity",
                    models.IntegerField(verbose_name="Quantidade de Rendimento"),
                ),
                (
                    "max_flavor_quantity",
                    models.IntegerField(
                        default=1, verbose_name="Quantidade Máxima de Sabores"
                    ),
                ),
                (
                    "min_quantity_per_flavor",
                    models.IntegerField(
                        default=1, verbose_name="Quantidade Mínima por Sabor"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "flavors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="products.flavor",
                        verbose_name="Sabores",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "prd_product",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductDataSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição da Ficha Técnica"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "flavor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sheets",
                        to="products.flavor",
                        verbose_name="Sabor",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sheets",
                        to="products.product",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha Técnica",
                "verbose_name_plural": "Fichas Técnicas",
                "db_table": "man_product_data_sheet",
                "ordering": ["product", "flavor"],
                "unique_together": {("product", "flavor")},
            },
        ),
        migrations.CreateModel(
            name="ProductionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantidade Produzida")),
                (
                    "product_data_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_items",
                        to="products.productdatasheet",
                        verbose_name="Ficha Técnica",
                    ),
                ),
                (
                    "production_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.productionbatch",
                        verbose_name="Lote de Produção",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Produção",
                "verbose_name_plural": "Items de Produção",
                "db_table": "man_production_item",
                "ordering": ["production_batch", "product_data_sheet"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome da Receita"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "measure_quantity",
                    models.FloatField(verbose_name="Quantidade de Rendimento"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "measure_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipes",
                        to="products.measureunit",
                        verbose_name="Medida de Rendimento",
                    ),
                ),
                (
                    "recipe_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipes",
                        to="products.recipecategory",
                        verbose_name="Categoria de Receita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
                "db_table": "man_recipe",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductDataSheetRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measure_quantity",
                    models.FloatField(verbose_name="Quantidade de Rendimento"),
                ),
                (
                    "data_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="products.productdatasheet",
                        verbose_name="Ficha Técnica",
                    ),
                ),
                (
                    "measure_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_sheet_measure_units",
                        to="products.measureunit",
                        verbose_name="Unidade de Medida",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sheet_recipes",
                        to="products.recipe",
                        verbose_name="Receita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita da Ficha Técnica",
                "verbose_name_plural": "Receitas da Ficha Técnica",
                "db_table": "man_product_data_sheet_recipe",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measure_quantity", models.FloatField(verbose_name="Quantidade")),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_recipes",
                        to="products.ingredient",
                        verbose_name="Ingrediente",
                    ),
                ),
                (
                    "measure_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measure_unit_recipes",
                        to="products.measureunit",
                        verbose_name="Unidade de Medida",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="products.recipe",
                        verbose_name="Receita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente da Receita",
                "verbose_name_plural": "Ingredientes da Receita",
                "db_table": "man_recipe_ingredient",
                "unique_together": {("recipe", "ingredient")},
            },
        ),
    ]
