# Generated by Django 5.2.2 on 2025-06-10 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_recipe_recipe_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="BakingPan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Forma"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("size", models.CharField(max_length=50, verbose_name="Tamanho")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Forma de Assar",
                "verbose_name_plural": "Formas de Assar",
                "db_table": "eqp_baking_pan",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipes",
                to="products.recipecategory",
                verbose_name="Categoria de Receita",
            ),
        ),
    ]
