# Generated by Django 5.2.2 on 2025-06-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productdatasheet_baking_pan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "ordering": ["recipe", "position"],
                "verbose_name": "Ingrediente da Receita",
                "verbose_name_plural": "Ingredientes da Receita",
            },
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="position",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Posição na Receita"
            ),
        ),
    ]
