# Generated by Django 5.2.2 on 2025-06-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_recipeingredient_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdatasheetrecipe",
            name="multiple",
            field=models.FloatField(default=1, verbose_name="Multiplicador"),
        ),
    ]
