# Generated by Django 5.2.2 on 2025-06-11 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productdatasheetrecipe_multiple"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdatasheet",
            name="baking_pan",
        ),
        migrations.AddField(
            model_name="productdatasheetrecipe",
            name="baking_pan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="data_sheets",
                to="products.bakingpan",
                verbose_name="Forma de Assar",
            ),
        ),
    ]
