# Generated by Django 5.2.2 on 2025-06-11 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_productdatasheet_baking_pan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdatasheetrecipe",
            name="baking_pan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="data_sheets",
                to="products.bakingpan",
                verbose_name="Forma de Assar",
            ),
        ),
        migrations.AlterField(
            model_name="productdatasheetrecipe",
            name="multiple",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Multiplicador"
            ),
        ),
    ]
