# Generated by Django 5.2.2 on 2025-06-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_productdatasheetrecipe_baking_pan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdatasheetrecipe",
            name="multiple",
            field=models.FloatField(default=1, verbose_name="Multiplicador"),
        ),
    ]
