# Generated by Django 5.2.2 on 2025-06-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_productdatasheetrecipe_multiple"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="yield_quantity",
        ),
    ]
