# Generated by Django 5.2.2 on 2025-06-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_remove_product_yield_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="yield_measure",
        ),
    ]
