# Generated by Django 5.2.2 on 2025-06-16 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_remove_category_yield_measure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdatasheetrecipe",
            name="measure_unit",
            field=models.ForeignKey(
                default="g",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="data_sheet_measure_units",
                to="products.measureunit",
                verbose_name="Unidade de Medida",
            ),
        ),
    ]
