# Generated by Django 5.2.2 on 2025-06-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_productdatasheetrecipe_measure_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="measure_unit",
            field=models.CharField(
                choices=[("g", "g"), ("kg", "kg")],
                default="g",
                max_length=10,
                verbose_name="Medida de Rendimento",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="measure_unit",
            field=models.CharField(
                choices=[("g", "g"), ("kg", "kg")],
                default="g",
                max_length=10,
                verbose_name="Medida de Rendimento",
            ),
        ),
        migrations.AlterField(
            model_name="productdatasheetrecipe",
            name="measure_unit",
            field=models.CharField(
                choices=[("g", "g"), ("kg", "kg")],
                default="g",
                max_length=10,
                verbose_name="Medida de Rendimento",
            ),
        ),
        migrations.DeleteModel(
            name="MeasureUnit",
        ),
    ]
